version: "3"
services:
  pricewatch:
    restart: always
    build: .
    env_file: .env
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.0
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db-data:/data/db

volumes:
  db-data:
